---
# tasks file for ansible
- name: Update OS
  include_tasks: update_os.yml

- name: Install VirtualBox for Debian dists
  block:
    - name: Install GPG Agent
      apt:
        name: gpg-agent
        state: present 

    - name: Add VirtualBox public key
      apt_key:
        url: "{{ virtualbox_apt_key }}"

    - name: Add VirtualBox APT repository
      apt_repository:
        repo: "{{ virtualbox_apt_repo }}"
      changed_when: false

    - name: Install VirtualBox
      apt:
        name: "{{ virtualbox_name_debian }}"
        state: present
  when: ansible_os_family == "Debian"
      
- name: Install VirtualBox for Centos dists
  block:
    - name: install VirtualBox packages
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ rehl_pkg }}"

    - name: Download VirtualBox
      get_url:
        url: "{{ virtualbox_link_redhat }}"
        dest: /etc/yum.repos.d/virtualbox.repo

    - name: Install VirtualBox for CentOS
      yum:
        name: "{{ virtualbox_name_redhat }}"
        state: present
  when: ansible_distribution == "Centos"

- name: Install VirtualBox for Fedora dists
  block:
    - name: Install VirtualBox packages
      dnf:
        name: "{{ item }}"
        state: present
      with_items: "{{ rehl_pkg }}"

    - name: Download virtualbox
      get_url:
        url: "{{ virtualbox_link_fedora }}"
        dest: /etc/yum.repos.d/virtualbox.repo

    - name: Install VirtualBox for Fedora
      dnf:
        name: "{{ virtualbox_name_fedora }}"
        state: present
  when: ansible_distribution == "Fedora"
